table 'Table (2)'
	lineageTag: e9c123ad-9847-45f4-97f0-f75e02d78d2d

	column Column1
		dataType: string
		lineageTag: effcd170-b8ec-45bf-86e6-07b6d09e8d9e
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 66df61a8-6045-42e4-b6b1-7187d2feb74d
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition 'Table (2)' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8inNTlRwyc9LzkxW0lHKKCkpKLbS1y8vL9crLkksyS0tTtVLzs/Vz0tK1E8szrYvtM0BatBOyc9TdTZRtXDJBFPm2kbGqkZuRibaxRn5JdrJGYlFJUqxsQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

